# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200227_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='username',
        ),
    ]
